In [46]:
import numpy
from sklearn import datasets, neighbors, model_selection
import pandas as pd
import numpy as np

In [3]:
iris = datasets.load_iris()

In [39]:
x = iris.data
y = iris.target
df = pd.DataFrame(iris.data, columns= ['sepal_length','sepal_width','petal_length','petal width'])
df['target'] = iris.target

In [22]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(x,y,test_size=.5, random_state=42)

In [26]:
classifier = neighbors.KNeighborsClassifier(n_neighbors=15)

In [27]:
classifier.fit(train_x, train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=15, p=2,
           weights='uniform')

In [29]:
classifier.score(test_x,test_y)

0.9733333333333334

In [48]:
df.head()

sepal_length  sepal_width  petal_length  petal width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [51]:
test = np.array([5.2,3.2,1.2,.18])
test1 = np.array([])
test = test.reshape(1,-1)
test

array([[5.2 , 3.2 , 1.2 , 0.18]])

In [54]:
classifier.predict(test_x)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 1])

In [55]:
test_y

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1])